// Code generated by go-swagger; DO NOT EDIT.

package archive

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gyk4j/toc/toc/server/models"
)

// GetArchiveByIDOKCode is the HTTP code returned for type GetArchiveByIDOK
const GetArchiveByIDOKCode int = 200

/*
GetArchiveByIDOK successful operation

swagger:response getArchiveByIdOK
*/
type GetArchiveByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Archive `json:"body,omitempty"`
}

// NewGetArchiveByIDOK creates GetArchiveByIDOK with default headers values
func NewGetArchiveByIDOK() *GetArchiveByIDOK {

	return &GetArchiveByIDOK{}
}

// WithPayload adds the payload to the get archive by Id o k response
func (o *GetArchiveByIDOK) WithPayload(payload *models.Archive) *GetArchiveByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get archive by Id o k response
func (o *GetArchiveByIDOK) SetPayload(payload *models.Archive) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArchiveByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetArchiveByIDBadRequestCode is the HTTP code returned for type GetArchiveByIDBadRequest
const GetArchiveByIDBadRequestCode int = 400

/*
GetArchiveByIDBadRequest Invalid ID supplied

swagger:response getArchiveByIdBadRequest
*/
type GetArchiveByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetArchiveByIDBadRequest creates GetArchiveByIDBadRequest with default headers values
func NewGetArchiveByIDBadRequest() *GetArchiveByIDBadRequest {

	return &GetArchiveByIDBadRequest{}
}

// WithPayload adds the payload to the get archive by Id bad request response
func (o *GetArchiveByIDBadRequest) WithPayload(payload *models.APIResponse) *GetArchiveByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get archive by Id bad request response
func (o *GetArchiveByIDBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArchiveByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetArchiveByIDNotFoundCode is the HTTP code returned for type GetArchiveByIDNotFound
const GetArchiveByIDNotFoundCode int = 404

/*
GetArchiveByIDNotFound Archive not found

swagger:response getArchiveByIdNotFound
*/
type GetArchiveByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetArchiveByIDNotFound creates GetArchiveByIDNotFound with default headers values
func NewGetArchiveByIDNotFound() *GetArchiveByIDNotFound {

	return &GetArchiveByIDNotFound{}
}

// WithPayload adds the payload to the get archive by Id not found response
func (o *GetArchiveByIDNotFound) WithPayload(payload *models.APIResponse) *GetArchiveByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get archive by Id not found response
func (o *GetArchiveByIDNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArchiveByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
