name: toc

services:
  web:
    build: ./web
    hostname: apache-server
    # depends_on:
      # - db
      # - file
    ports:
      - "8080:80"
      - "8443:443"
  db:
    build: ./db
    hostname: mysql-server
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
      - "33060:33060"
  file:
    build: ./file
    hostname: samba-server
    # restart: always
    environment:
      USER: user
      PASS: password
    ports:
      - "139:139"
      - "445:445"
  mail:
    build: ./mail
    hostname: apache-james-server
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "143:143"
      - "993:993"
  # dns:
    # build: ./dns
    # hostname: dnsmasq-server
    # environment:
      # DNS1: "1.0.0.1"
      # DNS2: "1.1.1.1"
    # ports:
      # - 53:53/udp
      # - 53:53/tcp
    # extra_hosts:
      # - "mail=192.168.56.10"
    # cap_add:
      # - NET_ADMIN
    # volumes:
      # - ./dns/dnsmasq.d/:/etc/dnsmasq.d/
      # - ./dns/dnsmasq.conf:/etc/dnsmasq.conf
      # - ./dns/banner_add_hosts:/etc/banner_add_hosts
  toc-frontend:
    build: ./toc-frontend
  toc-backend:
    build: ./toc-backend
  toc:
    build: ./toc
    hostname: toc-controller
    environment:
      HOST: 0.0.0.0
      PORT: 80
    ports:
      - "80:80"
    depends_on:
      - toc-frontend
      - toc-backend
      - web
      - db
      - file
      - mail
    extra_hosts:
      - "main:192.168.56.10"
      - "stepup:192.168.56.20"      
