name: toc

services:
  web:
    build: ./web
    hostname: apache-server
    depends_on:
      - db
      - file
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./mount/storage:/storage"
      # - type: volume
        # source: cms-files
        # target: /storage
    # networks:
      # static_net:
        # ipv4_address: 10.5.1.1
  db:
    build: ./db
    hostname: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
      - "33060:33060"
    # networks:
      # static_net:
        # ipv4_address: 10.5.1.2
  file:
    build: ./file
    hostname: samba-server
    restart: always
    environment:
      USER: user
      PASS: password
    ports:
      - "445:445"
    volumes:
      - "./mount/storage:/storage"
    # networks:
      # static_net:
        # ipv4_address: 10.5.1.3
  mail:
    build: ./mail
    hostname: apache-james-server
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "143:143"
      - "993:993"
    volumes:
      - "./mount/mail:/root/var"
    # networks:
      # static_net:
        # ipv4_address: 10.5.1.4
  # dns:
    # build: ./dns
    # hostname: dnsmasq-server
    # environment:
      # DNS1: "1.0.0.1"
      # DNS2: "1.1.1.1"
    # ports:
      # - 53:53/udp
      # - 53:53/tcp
    # extra_hosts:
      # - "mail=192.168.56.10"
    # cap_add:
      # - NET_ADMIN
    # volumes:
      # - ./dns/dnsmasq.d/:/etc/dnsmasq.d/
      # - ./dns/dnsmasq.conf:/etc/dnsmasq.conf
      # - ./dns/banner_add_hosts:/etc/banner_add_hosts
  toc:
    build: ./toc
    hostname: toc-controller
    depends_on:
      - web
      - db
      - file
      - mail
    volumes:
      - .:/opt/toc/
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "main:192.168.56.10"
      - "stepup:192.168.56.20"
    # networks:
      # static_net:
        # ipv4_address: 10.5.1.5
      
# volumes:
  # cms-files:
    # name: cms-files
    # driver: local
    # driver_opts:
      # type: "cifs"
      # device: "//10.5.1.3/Data"
      # o: "addr=10.5.1.3,username=user,password=password,file_mode=0777,dir_mode=0777"
      
# networks:
  # static_net:
    # driver: bridge
    # ipam:
      # config:
        # - subnet: 10.5.0.0/16
          # gateway: 10.5.0.1
      
