services:
  web:
    build: ./web
    ports:
      - "80:80"
      - "443:443"
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
      - "33060:33060"
