services:
  web:
    build: ./web
    depends_on:
      - db
      - file
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./mount/storage:/storage"
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
      - "33060:33060"
  file:
    build: ./file
    restart: always
    environment:
      USER: user
      PASS: password
    ports:
      - "445:445"
    volumes:
      - "./mount/storage:/storage"
  mail:
    build: ./mail 
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "143:143"
      - "993:993"
    volumes:
      - "./mount/mail:/root/var"
  dns:
    build: ./dns
    environment:
      DNS1: "1.0.0.1"
      DNS2: "1.1.1.1"
    ports:
      - 53:53/udp
      - 53:53/tcp
    extra_hosts:
      - "mail=192.168.56.10"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dns/dnsmasq.d/:/etc/dnsmasq.d/
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf
      - ./dns/banner_add_hosts:/etc/banner_add_hosts
