/*
 * TOC API
 *
 * An API to create backup and restoration
 *
 * API version: 1.0.0
 * Contact: 147011991+gyk4j@users.noreply.github.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Severity string

// List of Severity
const (
	ERROR_ Severity = "error"
	WARNING Severity = "warning"
	INFO Severity = "info"
	DEBUG Severity = "debug"
	TRACE Severity = "trace"
)
