/*
 * TOC API
 *
 * An API to create backup and restoration
 *
 * API version: 1.0.0
 * Contact: 147011991+gyk4j@users.noreply.github.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Snapshot struct {

	Id int64 `json:"id,omitempty"`

	File string `json:"file,omitempty"`

	// Snapshot Status
	Status string `json:"status,omitempty"`

	Complete bool `json:"complete,omitempty"`
}
