// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTransferHandlerFunc turns a function with the right signature into a get transfer handler
type GetTransferHandlerFunc func(GetTransferParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTransferHandlerFunc) Handle(params GetTransferParams) middleware.Responder {
	return fn(params)
}

// GetTransferHandler interface for that can handle valid get transfer params
type GetTransferHandler interface {
	Handle(GetTransferParams) middleware.Responder
}

// NewGetTransfer creates a new http.Handler for the get transfer operation
func NewGetTransfer(ctx *middleware.Context, handler GetTransferHandler) *GetTransfer {
	return &GetTransfer{Context: ctx, Handler: handler}
}

/*
	GetTransfer swagger:route GET /transfers transfer getTransfer

# Query transfer status

Retrieve status of all transfers
*/
type GetTransfer struct {
	Context *middleware.Context
	Handler GetTransferHandler
}

func (o *GetTransfer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTransferParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
