// Code generated by go-swagger; DO NOT EDIT.

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetQuotasHandlerFunc turns a function with the right signature into a get quotas handler
type GetQuotasHandlerFunc func(GetQuotasParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetQuotasHandlerFunc) Handle(params GetQuotasParams) middleware.Responder {
	return fn(params)
}

// GetQuotasHandler interface for that can handle valid get quotas params
type GetQuotasHandler interface {
	Handle(GetQuotasParams) middleware.Responder
}

// NewGetQuotas creates a new http.Handler for the get quotas operation
func NewGetQuotas(ctx *middleware.Context, handler GetQuotasHandler) *GetQuotas {
	return &GetQuotas{Context: ctx, Handler: handler}
}

/*
	GetQuotas swagger:route GET /quotas quota getQuotas

# Refresh quota info

Retrieve all quotas set
*/
type GetQuotas struct {
	Context *middleware.Context
	Handler GetQuotasHandler
}

func (o *GetQuotas) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetQuotasParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
