// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTransfersHandlerFunc turns a function with the right signature into a get transfers handler
type GetTransfersHandlerFunc func(GetTransfersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTransfersHandlerFunc) Handle(params GetTransfersParams) middleware.Responder {
	return fn(params)
}

// GetTransfersHandler interface for that can handle valid get transfers params
type GetTransfersHandler interface {
	Handle(GetTransfersParams) middleware.Responder
}

// NewGetTransfers creates a new http.Handler for the get transfers operation
func NewGetTransfers(ctx *middleware.Context, handler GetTransfersHandler) *GetTransfers {
	return &GetTransfers{Context: ctx, Handler: handler}
}

/*
	GetTransfers swagger:route GET /transfers transfer getTransfers

# Query transfer status

Retrieve status of all transfers
*/
type GetTransfers struct {
	Context *middleware.Context
	Handler GetTransfersHandler
}

func (o *GetTransfers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTransfersParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
