// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gyk4j/toc/toc-backend/models"
)

// GetTransfersOKCode is the HTTP code returned for type GetTransfersOK
const GetTransfersOKCode int = 200

/*
GetTransfersOK Transfer info retrieved

swagger:response getTransfersOK
*/
type GetTransfersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Transfer `json:"body,omitempty"`
}

// NewGetTransfersOK creates GetTransfersOK with default headers values
func NewGetTransfersOK() *GetTransfersOK {

	return &GetTransfersOK{}
}

// WithPayload adds the payload to the get transfers o k response
func (o *GetTransfersOK) WithPayload(payload []*models.Transfer) *GetTransfersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transfers o k response
func (o *GetTransfersOK) SetPayload(payload []*models.Transfer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransfersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Transfer, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetTransfersForbiddenCode is the HTTP code returned for type GetTransfersForbidden
const GetTransfersForbiddenCode int = 403

/*
GetTransfersForbidden Forbidden from querying transfer status

swagger:response getTransfersForbidden
*/
type GetTransfersForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetTransfersForbidden creates GetTransfersForbidden with default headers values
func NewGetTransfersForbidden() *GetTransfersForbidden {

	return &GetTransfersForbidden{}
}

// WithPayload adds the payload to the get transfers forbidden response
func (o *GetTransfersForbidden) WithPayload(payload *models.APIResponse) *GetTransfersForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transfers forbidden response
func (o *GetTransfersForbidden) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransfersForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTransfersNotFoundCode is the HTTP code returned for type GetTransfersNotFound
const GetTransfersNotFoundCode int = 404

/*
GetTransfersNotFound Transfer not found

swagger:response getTransfersNotFound
*/
type GetTransfersNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetTransfersNotFound creates GetTransfersNotFound with default headers values
func NewGetTransfersNotFound() *GetTransfersNotFound {

	return &GetTransfersNotFound{}
}

// WithPayload adds the payload to the get transfers not found response
func (o *GetTransfersNotFound) WithPayload(payload *models.APIResponse) *GetTransfersNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transfers not found response
func (o *GetTransfersNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransfersNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTransfersMethodNotAllowedCode is the HTTP code returned for type GetTransfersMethodNotAllowed
const GetTransfersMethodNotAllowedCode int = 405

/*
GetTransfersMethodNotAllowed Bad request

swagger:response getTransfersMethodNotAllowed
*/
type GetTransfersMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetTransfersMethodNotAllowed creates GetTransfersMethodNotAllowed with default headers values
func NewGetTransfersMethodNotAllowed() *GetTransfersMethodNotAllowed {

	return &GetTransfersMethodNotAllowed{}
}

// WithPayload adds the payload to the get transfers method not allowed response
func (o *GetTransfersMethodNotAllowed) WithPayload(payload *models.APIResponse) *GetTransfersMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transfers method not allowed response
func (o *GetTransfersMethodNotAllowed) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransfersMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTransfersInternalServerErrorCode is the HTTP code returned for type GetTransfersInternalServerError
const GetTransfersInternalServerErrorCode int = 500

/*
GetTransfersInternalServerError TOC controller error

swagger:response getTransfersInternalServerError
*/
type GetTransfersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetTransfersInternalServerError creates GetTransfersInternalServerError with default headers values
func NewGetTransfersInternalServerError() *GetTransfersInternalServerError {

	return &GetTransfersInternalServerError{}
}

// WithPayload adds the payload to the get transfers internal server error response
func (o *GetTransfersInternalServerError) WithPayload(payload *models.APIResponse) *GetTransfersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transfers internal server error response
func (o *GetTransfersInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransfersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTransfersServiceUnavailableCode is the HTTP code returned for type GetTransfersServiceUnavailable
const GetTransfersServiceUnavailableCode int = 503

/*
GetTransfersServiceUnavailable Service unavailable

swagger:response getTransfersServiceUnavailable
*/
type GetTransfersServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetTransfersServiceUnavailable creates GetTransfersServiceUnavailable with default headers values
func NewGetTransfersServiceUnavailable() *GetTransfersServiceUnavailable {

	return &GetTransfersServiceUnavailable{}
}

// WithPayload adds the payload to the get transfers service unavailable response
func (o *GetTransfersServiceUnavailable) WithPayload(payload *models.APIResponse) *GetTransfersServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transfers service unavailable response
func (o *GetTransfersServiceUnavailable) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransfersServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
