// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateTransferHandlerFunc turns a function with the right signature into a update transfer handler
type UpdateTransferHandlerFunc func(UpdateTransferParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateTransferHandlerFunc) Handle(params UpdateTransferParams) middleware.Responder {
	return fn(params)
}

// UpdateTransferHandler interface for that can handle valid update transfer params
type UpdateTransferHandler interface {
	Handle(UpdateTransferParams) middleware.Responder
}

// NewUpdateTransfer creates a new http.Handler for the update transfer operation
func NewUpdateTransfer(ctx *middleware.Context, handler UpdateTransferHandler) *UpdateTransfer {
	return &UpdateTransfer{Context: ctx, Handler: handler}
}

/*
	UpdateTransfer swagger:route PUT /transfers transfer updateTransfer

Update transfer status/info

Update transfer status/info
*/
type UpdateTransfer struct {
	Context *middleware.Context
	Handler UpdateTransferHandler
}

func (o *UpdateTransfer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateTransferParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
