// Code generated by go-swagger; DO NOT EDIT.

package archive

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetArchiveByIDParams creates a new GetArchiveByIDParams object
//
// There are no default values defined in the spec.
func NewGetArchiveByIDParams() GetArchiveByIDParams {

	return GetArchiveByIDParams{}
}

// GetArchiveByIDParams contains all the bound params for the get archive by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters getArchiveById
type GetArchiveByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of archive to return
	  Required: true
	  In: path
	*/
	ArchiveID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetArchiveByIDParams() beforehand.
func (o *GetArchiveByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rArchiveID, rhkArchiveID, _ := route.Params.GetOK("archiveId")
	if err := o.bindArchiveID(rArchiveID, rhkArchiveID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindArchiveID binds and validates parameter ArchiveID from path.
func (o *GetArchiveByIDParams) bindArchiveID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("archiveId", "path", "int64", raw)
	}
	o.ArchiveID = value

	return nil
}
