// Code generated by go-swagger; DO NOT EDIT.

package restoration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRestorationByIDParams creates a new GetRestorationByIDParams object
//
// There are no default values defined in the spec.
func NewGetRestorationByIDParams() GetRestorationByIDParams {

	return GetRestorationByIDParams{}
}

// GetRestorationByIDParams contains all the bound params for the get restoration by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters getRestorationById
type GetRestorationByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of restoration to return
	  Required: true
	  In: path
	*/
	RestorationID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetRestorationByIDParams() beforehand.
func (o *GetRestorationByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRestorationID, rhkRestorationID, _ := route.Params.GetOK("restorationId")
	if err := o.bindRestorationID(rRestorationID, rhkRestorationID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRestorationID binds and validates parameter RestorationID from path.
func (o *GetRestorationByIDParams) bindRestorationID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("restorationId", "path", "int64", raw)
	}
	o.RestorationID = value

	return nil
}
