// Code generated by go-swagger; DO NOT EDIT.

package restoration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gyk4j/toc/toc-agent/models"
)

// NewRestorationOKCode is the HTTP code returned for type NewRestorationOK
const NewRestorationOKCode int = 200

/*
NewRestorationOK Restoration started

swagger:response newRestorationOK
*/
type NewRestorationOK struct {

	/*
	  In: Body
	*/
	Payload *models.Restoration `json:"body,omitempty"`
}

// NewNewRestorationOK creates NewRestorationOK with default headers values
func NewNewRestorationOK() *NewRestorationOK {

	return &NewRestorationOK{}
}

// WithPayload adds the payload to the new restoration o k response
func (o *NewRestorationOK) WithPayload(payload *models.Restoration) *NewRestorationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new restoration o k response
func (o *NewRestorationOK) SetPayload(payload *models.Restoration) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewRestorationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// NewRestorationForbiddenCode is the HTTP code returned for type NewRestorationForbidden
const NewRestorationForbiddenCode int = 403

/*
NewRestorationForbidden Forbidden from creating duplicate/repeat restoration

swagger:response newRestorationForbidden
*/
type NewRestorationForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewNewRestorationForbidden creates NewRestorationForbidden with default headers values
func NewNewRestorationForbidden() *NewRestorationForbidden {

	return &NewRestorationForbidden{}
}

// WithPayload adds the payload to the new restoration forbidden response
func (o *NewRestorationForbidden) WithPayload(payload *models.APIResponse) *NewRestorationForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new restoration forbidden response
func (o *NewRestorationForbidden) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewRestorationForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// NewRestorationNotFoundCode is the HTTP code returned for type NewRestorationNotFound
const NewRestorationNotFoundCode int = 404

/*
NewRestorationNotFound Stepup backup server not found

swagger:response newRestorationNotFound
*/
type NewRestorationNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewNewRestorationNotFound creates NewRestorationNotFound with default headers values
func NewNewRestorationNotFound() *NewRestorationNotFound {

	return &NewRestorationNotFound{}
}

// WithPayload adds the payload to the new restoration not found response
func (o *NewRestorationNotFound) WithPayload(payload *models.APIResponse) *NewRestorationNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new restoration not found response
func (o *NewRestorationNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewRestorationNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// NewRestorationMethodNotAllowedCode is the HTTP code returned for type NewRestorationMethodNotAllowed
const NewRestorationMethodNotAllowedCode int = 405

/*
NewRestorationMethodNotAllowed Bad request

swagger:response newRestorationMethodNotAllowed
*/
type NewRestorationMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewNewRestorationMethodNotAllowed creates NewRestorationMethodNotAllowed with default headers values
func NewNewRestorationMethodNotAllowed() *NewRestorationMethodNotAllowed {

	return &NewRestorationMethodNotAllowed{}
}

// WithPayload adds the payload to the new restoration method not allowed response
func (o *NewRestorationMethodNotAllowed) WithPayload(payload *models.APIResponse) *NewRestorationMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new restoration method not allowed response
func (o *NewRestorationMethodNotAllowed) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewRestorationMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// NewRestorationInternalServerErrorCode is the HTTP code returned for type NewRestorationInternalServerError
const NewRestorationInternalServerErrorCode int = 500

/*
NewRestorationInternalServerError Stepup TOC controller error

swagger:response newRestorationInternalServerError
*/
type NewRestorationInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewNewRestorationInternalServerError creates NewRestorationInternalServerError with default headers values
func NewNewRestorationInternalServerError() *NewRestorationInternalServerError {

	return &NewRestorationInternalServerError{}
}

// WithPayload adds the payload to the new restoration internal server error response
func (o *NewRestorationInternalServerError) WithPayload(payload *models.APIResponse) *NewRestorationInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new restoration internal server error response
func (o *NewRestorationInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewRestorationInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// NewRestorationBadGatewayCode is the HTTP code returned for type NewRestorationBadGateway
const NewRestorationBadGatewayCode int = 502

/*
NewRestorationBadGateway Bad gateway. Stepup backup server error

swagger:response newRestorationBadGateway
*/
type NewRestorationBadGateway struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewNewRestorationBadGateway creates NewRestorationBadGateway with default headers values
func NewNewRestorationBadGateway() *NewRestorationBadGateway {

	return &NewRestorationBadGateway{}
}

// WithPayload adds the payload to the new restoration bad gateway response
func (o *NewRestorationBadGateway) WithPayload(payload *models.APIResponse) *NewRestorationBadGateway {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new restoration bad gateway response
func (o *NewRestorationBadGateway) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewRestorationBadGateway) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(502)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// NewRestorationServiceUnavailableCode is the HTTP code returned for type NewRestorationServiceUnavailable
const NewRestorationServiceUnavailableCode int = 503

/*
NewRestorationServiceUnavailable Service unavailable on stepup TOC controller

swagger:response newRestorationServiceUnavailable
*/
type NewRestorationServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewNewRestorationServiceUnavailable creates NewRestorationServiceUnavailable with default headers values
func NewNewRestorationServiceUnavailable() *NewRestorationServiceUnavailable {

	return &NewRestorationServiceUnavailable{}
}

// WithPayload adds the payload to the new restoration service unavailable response
func (o *NewRestorationServiceUnavailable) WithPayload(payload *models.APIResponse) *NewRestorationServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new restoration service unavailable response
func (o *NewRestorationServiceUnavailable) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewRestorationServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// NewRestorationGatewayTimeoutCode is the HTTP code returned for type NewRestorationGatewayTimeout
const NewRestorationGatewayTimeoutCode int = 504

/*
NewRestorationGatewayTimeout Gateway timeout. Stepup backup server did not reply.

swagger:response newRestorationGatewayTimeout
*/
type NewRestorationGatewayTimeout struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewNewRestorationGatewayTimeout creates NewRestorationGatewayTimeout with default headers values
func NewNewRestorationGatewayTimeout() *NewRestorationGatewayTimeout {

	return &NewRestorationGatewayTimeout{}
}

// WithPayload adds the payload to the new restoration gateway timeout response
func (o *NewRestorationGatewayTimeout) WithPayload(payload *models.APIResponse) *NewRestorationGatewayTimeout {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new restoration gateway timeout response
func (o *NewRestorationGatewayTimeout) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewRestorationGatewayTimeout) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(504)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
