// Code generated by go-swagger; DO NOT EDIT.

package synchronization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateSynchronizationHandlerFunc turns a function with the right signature into a update synchronization handler
type UpdateSynchronizationHandlerFunc func(UpdateSynchronizationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateSynchronizationHandlerFunc) Handle(params UpdateSynchronizationParams) middleware.Responder {
	return fn(params)
}

// UpdateSynchronizationHandler interface for that can handle valid update synchronization params
type UpdateSynchronizationHandler interface {
	Handle(UpdateSynchronizationParams) middleware.Responder
}

// NewUpdateSynchronization creates a new http.Handler for the update synchronization operation
func NewUpdateSynchronization(ctx *middleware.Context, handler UpdateSynchronizationHandler) *UpdateSynchronization {
	return &UpdateSynchronization{Context: ctx, Handler: handler}
}

/*
	UpdateSynchronization swagger:route PUT /synchronizations synchronization updateSynchronization

Update synchronization status/info

Update synchronization status/info
*/
type UpdateSynchronization struct {
	Context *middleware.Context
	Handler UpdateSynchronizationHandler
}

func (o *UpdateSynchronization) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateSynchronizationParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
