// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBackupByIDParams creates a new GetBackupByIDParams object
//
// There are no default values defined in the spec.
func NewGetBackupByIDParams() GetBackupByIDParams {

	return GetBackupByIDParams{}
}

// GetBackupByIDParams contains all the bound params for the get backup by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters getBackupById
type GetBackupByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of backup to return
	  Required: true
	  In: path
	*/
	BackupID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetBackupByIDParams() beforehand.
func (o *GetBackupByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBackupID, rhkBackupID, _ := route.Params.GetOK("backupId")
	if err := o.bindBackupID(rBackupID, rhkBackupID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBackupID binds and validates parameter BackupID from path.
func (o *GetBackupByIDParams) bindBackupID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("backupId", "path", "int64", raw)
	}
	o.BackupID = value

	return nil
}
