// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBackupByIDHandlerFunc turns a function with the right signature into a get backup by Id handler
type GetBackupByIDHandlerFunc func(GetBackupByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBackupByIDHandlerFunc) Handle(params GetBackupByIDParams) middleware.Responder {
	return fn(params)
}

// GetBackupByIDHandler interface for that can handle valid get backup by Id params
type GetBackupByIDHandler interface {
	Handle(GetBackupByIDParams) middleware.Responder
}

// NewGetBackupByID creates a new http.Handler for the get backup by Id operation
func NewGetBackupByID(ctx *middleware.Context, handler GetBackupByIDHandler) *GetBackupByID {
	return &GetBackupByID{Context: ctx, Handler: handler}
}

/*
	GetBackupByID swagger:route GET /backups/{backupId} backup getBackupById

# Find backup by ID

Query a single backup
*/
type GetBackupByID struct {
	Context *middleware.Context
	Handler GetBackupByIDHandler
}

func (o *GetBackupByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBackupByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
