// Code generated by go-swagger; DO NOT EDIT.

package restoration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRestorationHandlerFunc turns a function with the right signature into a get restoration handler
type GetRestorationHandlerFunc func(GetRestorationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRestorationHandlerFunc) Handle(params GetRestorationParams) middleware.Responder {
	return fn(params)
}

// GetRestorationHandler interface for that can handle valid get restoration params
type GetRestorationHandler interface {
	Handle(GetRestorationParams) middleware.Responder
}

// NewGetRestoration creates a new http.Handler for the get restoration operation
func NewGetRestoration(ctx *middleware.Context, handler GetRestorationHandler) *GetRestoration {
	return &GetRestoration{Context: ctx, Handler: handler}
}

/*
	GetRestoration swagger:route GET /restorations restoration getRestoration

# Query restoration info

Retrieve information and state of all restorations, their backup and snapshots
*/
type GetRestoration struct {
	Context *middleware.Context
	Handler GetRestorationHandler
}

func (o *GetRestoration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetRestorationParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
