// Code generated by go-swagger; DO NOT EDIT.

package restoration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRestorationByIDHandlerFunc turns a function with the right signature into a get restoration by Id handler
type GetRestorationByIDHandlerFunc func(GetRestorationByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRestorationByIDHandlerFunc) Handle(params GetRestorationByIDParams) middleware.Responder {
	return fn(params)
}

// GetRestorationByIDHandler interface for that can handle valid get restoration by Id params
type GetRestorationByIDHandler interface {
	Handle(GetRestorationByIDParams) middleware.Responder
}

// NewGetRestorationByID creates a new http.Handler for the get restoration by Id operation
func NewGetRestorationByID(ctx *middleware.Context, handler GetRestorationByIDHandler) *GetRestorationByID {
	return &GetRestorationByID{Context: ctx, Handler: handler}
}

/*
	GetRestorationByID swagger:route GET /restorations/{restorationId} restoration getRestorationById

# Find restoration by ID

Query a single restoration
*/
type GetRestorationByID struct {
	Context *middleware.Context
	Handler GetRestorationByIDHandler
}

func (o *GetRestorationByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetRestorationByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
