// Code generated by go-swagger; DO NOT EDIT.

package archive

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ArchiveDataHandlerFunc turns a function with the right signature into a archive data handler
type ArchiveDataHandlerFunc func(ArchiveDataParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ArchiveDataHandlerFunc) Handle(params ArchiveDataParams) middleware.Responder {
	return fn(params)
}

// ArchiveDataHandler interface for that can handle valid archive data params
type ArchiveDataHandler interface {
	Handle(ArchiveDataParams) middleware.Responder
}

// NewArchiveData creates a new http.Handler for the archive data operation
func NewArchiveData(ctx *middleware.Context, handler ArchiveDataHandler) *ArchiveData {
	return &ArchiveData{Context: ctx, Handler: handler}
}

/*
	ArchiveData swagger:route POST /archives archive archiveData

# Archive data

Create a ZIP archive of backup snapshot data
*/
type ArchiveData struct {
	Context *middleware.Context
	Handler ArchiveDataHandler
}

func (o *ArchiveData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewArchiveDataParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
