// Code generated by go-swagger; DO NOT EDIT.

package archive

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateArchiveHandlerFunc turns a function with the right signature into a update archive handler
type UpdateArchiveHandlerFunc func(UpdateArchiveParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateArchiveHandlerFunc) Handle(params UpdateArchiveParams) middleware.Responder {
	return fn(params)
}

// UpdateArchiveHandler interface for that can handle valid update archive params
type UpdateArchiveHandler interface {
	Handle(UpdateArchiveParams) middleware.Responder
}

// NewUpdateArchive creates a new http.Handler for the update archive operation
func NewUpdateArchive(ctx *middleware.Context, handler UpdateArchiveHandler) *UpdateArchive {
	return &UpdateArchive{Context: ctx, Handler: handler}
}

/*
	UpdateArchive swagger:route PUT /archives archive updateArchive

Update archive status/info

Update archive status/info
*/
type UpdateArchive struct {
	Context *middleware.Context
	Handler UpdateArchiveHandler
}

func (o *UpdateArchive) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateArchiveParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
