// Code generated by go-swagger; DO NOT EDIT.

// Package restapi toc
//
//	An API to create backup and restoration
//	Terms Of Service:
//	  http://gyk4j.github.io/terms/
//	Schemes:
//	  http
//	Host: 127.0.0.1:8080
//	BasePath: /v1
//	Version: 1.0.0
//	License: Eclipse Public License 2.0 (EPL) https://www.eclipse.org/legal/epl-2.0/
//	Contact: <147011991+gyk4j@users.noreply.github.com>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
