// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gyk4j/toc/toc/models"
)

// GetBackupOKCode is the HTTP code returned for type GetBackupOK
const GetBackupOKCode int = 200

/*
GetBackupOK Backup info retrieved

swagger:response getBackupOK
*/
type GetBackupOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Backup `json:"body,omitempty"`
}

// NewGetBackupOK creates GetBackupOK with default headers values
func NewGetBackupOK() *GetBackupOK {

	return &GetBackupOK{}
}

// WithPayload adds the payload to the get backup o k response
func (o *GetBackupOK) WithPayload(payload []*models.Backup) *GetBackupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backup o k response
func (o *GetBackupOK) SetPayload(payload []*models.Backup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Backup, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBackupForbiddenCode is the HTTP code returned for type GetBackupForbidden
const GetBackupForbiddenCode int = 403

/*
GetBackupForbidden Forbidden from querying backup info

swagger:response getBackupForbidden
*/
type GetBackupForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBackupForbidden creates GetBackupForbidden with default headers values
func NewGetBackupForbidden() *GetBackupForbidden {

	return &GetBackupForbidden{}
}

// WithPayload adds the payload to the get backup forbidden response
func (o *GetBackupForbidden) WithPayload(payload *models.APIResponse) *GetBackupForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backup forbidden response
func (o *GetBackupForbidden) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBackupNotFoundCode is the HTTP code returned for type GetBackupNotFound
const GetBackupNotFoundCode int = 404

/*
GetBackupNotFound Backup not found

swagger:response getBackupNotFound
*/
type GetBackupNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBackupNotFound creates GetBackupNotFound with default headers values
func NewGetBackupNotFound() *GetBackupNotFound {

	return &GetBackupNotFound{}
}

// WithPayload adds the payload to the get backup not found response
func (o *GetBackupNotFound) WithPayload(payload *models.APIResponse) *GetBackupNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backup not found response
func (o *GetBackupNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBackupMethodNotAllowedCode is the HTTP code returned for type GetBackupMethodNotAllowed
const GetBackupMethodNotAllowedCode int = 405

/*
GetBackupMethodNotAllowed Bad request

swagger:response getBackupMethodNotAllowed
*/
type GetBackupMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBackupMethodNotAllowed creates GetBackupMethodNotAllowed with default headers values
func NewGetBackupMethodNotAllowed() *GetBackupMethodNotAllowed {

	return &GetBackupMethodNotAllowed{}
}

// WithPayload adds the payload to the get backup method not allowed response
func (o *GetBackupMethodNotAllowed) WithPayload(payload *models.APIResponse) *GetBackupMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backup method not allowed response
func (o *GetBackupMethodNotAllowed) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBackupInternalServerErrorCode is the HTTP code returned for type GetBackupInternalServerError
const GetBackupInternalServerErrorCode int = 500

/*
GetBackupInternalServerError TOC controller error

swagger:response getBackupInternalServerError
*/
type GetBackupInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBackupInternalServerError creates GetBackupInternalServerError with default headers values
func NewGetBackupInternalServerError() *GetBackupInternalServerError {

	return &GetBackupInternalServerError{}
}

// WithPayload adds the payload to the get backup internal server error response
func (o *GetBackupInternalServerError) WithPayload(payload *models.APIResponse) *GetBackupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backup internal server error response
func (o *GetBackupInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBackupServiceUnavailableCode is the HTTP code returned for type GetBackupServiceUnavailable
const GetBackupServiceUnavailableCode int = 503

/*
GetBackupServiceUnavailable Service unavailable

swagger:response getBackupServiceUnavailable
*/
type GetBackupServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBackupServiceUnavailable creates GetBackupServiceUnavailable with default headers values
func NewGetBackupServiceUnavailable() *GetBackupServiceUnavailable {

	return &GetBackupServiceUnavailable{}
}

// WithPayload adds the payload to the get backup service unavailable response
func (o *GetBackupServiceUnavailable) WithPayload(payload *models.APIResponse) *GetBackupServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backup service unavailable response
func (o *GetBackupServiceUnavailable) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
