// Code generated by go-swagger; DO NOT EDIT.

package restoration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gyk4j/toc/toc-backend/models"
)

// UpdateRestorationOKCode is the HTTP code returned for type UpdateRestorationOK
const UpdateRestorationOKCode int = 200

/*
UpdateRestorationOK Restoration updated

swagger:response updateRestorationOK
*/
type UpdateRestorationOK struct {

	/*
	  In: Body
	*/
	Payload *models.Restoration `json:"body,omitempty"`
}

// NewUpdateRestorationOK creates UpdateRestorationOK with default headers values
func NewUpdateRestorationOK() *UpdateRestorationOK {

	return &UpdateRestorationOK{}
}

// WithPayload adds the payload to the update restoration o k response
func (o *UpdateRestorationOK) WithPayload(payload *models.Restoration) *UpdateRestorationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update restoration o k response
func (o *UpdateRestorationOK) SetPayload(payload *models.Restoration) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRestorationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRestorationForbiddenCode is the HTTP code returned for type UpdateRestorationForbidden
const UpdateRestorationForbiddenCode int = 403

/*
UpdateRestorationForbidden Forbidden from updating restoration

swagger:response updateRestorationForbidden
*/
type UpdateRestorationForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateRestorationForbidden creates UpdateRestorationForbidden with default headers values
func NewUpdateRestorationForbidden() *UpdateRestorationForbidden {

	return &UpdateRestorationForbidden{}
}

// WithPayload adds the payload to the update restoration forbidden response
func (o *UpdateRestorationForbidden) WithPayload(payload *models.APIResponse) *UpdateRestorationForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update restoration forbidden response
func (o *UpdateRestorationForbidden) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRestorationForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRestorationNotFoundCode is the HTTP code returned for type UpdateRestorationNotFound
const UpdateRestorationNotFoundCode int = 404

/*
UpdateRestorationNotFound TOC controller not found

swagger:response updateRestorationNotFound
*/
type UpdateRestorationNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateRestorationNotFound creates UpdateRestorationNotFound with default headers values
func NewUpdateRestorationNotFound() *UpdateRestorationNotFound {

	return &UpdateRestorationNotFound{}
}

// WithPayload adds the payload to the update restoration not found response
func (o *UpdateRestorationNotFound) WithPayload(payload *models.APIResponse) *UpdateRestorationNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update restoration not found response
func (o *UpdateRestorationNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRestorationNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRestorationMethodNotAllowedCode is the HTTP code returned for type UpdateRestorationMethodNotAllowed
const UpdateRestorationMethodNotAllowedCode int = 405

/*
UpdateRestorationMethodNotAllowed Bad request

swagger:response updateRestorationMethodNotAllowed
*/
type UpdateRestorationMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateRestorationMethodNotAllowed creates UpdateRestorationMethodNotAllowed with default headers values
func NewUpdateRestorationMethodNotAllowed() *UpdateRestorationMethodNotAllowed {

	return &UpdateRestorationMethodNotAllowed{}
}

// WithPayload adds the payload to the update restoration method not allowed response
func (o *UpdateRestorationMethodNotAllowed) WithPayload(payload *models.APIResponse) *UpdateRestorationMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update restoration method not allowed response
func (o *UpdateRestorationMethodNotAllowed) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRestorationMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRestorationInternalServerErrorCode is the HTTP code returned for type UpdateRestorationInternalServerError
const UpdateRestorationInternalServerErrorCode int = 500

/*
UpdateRestorationInternalServerError TOC controller error

swagger:response updateRestorationInternalServerError
*/
type UpdateRestorationInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateRestorationInternalServerError creates UpdateRestorationInternalServerError with default headers values
func NewUpdateRestorationInternalServerError() *UpdateRestorationInternalServerError {

	return &UpdateRestorationInternalServerError{}
}

// WithPayload adds the payload to the update restoration internal server error response
func (o *UpdateRestorationInternalServerError) WithPayload(payload *models.APIResponse) *UpdateRestorationInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update restoration internal server error response
func (o *UpdateRestorationInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRestorationInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRestorationBadGatewayCode is the HTTP code returned for type UpdateRestorationBadGateway
const UpdateRestorationBadGatewayCode int = 502

/*
UpdateRestorationBadGateway Bad gateway. TOC controller error

swagger:response updateRestorationBadGateway
*/
type UpdateRestorationBadGateway struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateRestorationBadGateway creates UpdateRestorationBadGateway with default headers values
func NewUpdateRestorationBadGateway() *UpdateRestorationBadGateway {

	return &UpdateRestorationBadGateway{}
}

// WithPayload adds the payload to the update restoration bad gateway response
func (o *UpdateRestorationBadGateway) WithPayload(payload *models.APIResponse) *UpdateRestorationBadGateway {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update restoration bad gateway response
func (o *UpdateRestorationBadGateway) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRestorationBadGateway) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(502)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRestorationServiceUnavailableCode is the HTTP code returned for type UpdateRestorationServiceUnavailable
const UpdateRestorationServiceUnavailableCode int = 503

/*
UpdateRestorationServiceUnavailable Service unavailable on TOC controller

swagger:response updateRestorationServiceUnavailable
*/
type UpdateRestorationServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateRestorationServiceUnavailable creates UpdateRestorationServiceUnavailable with default headers values
func NewUpdateRestorationServiceUnavailable() *UpdateRestorationServiceUnavailable {

	return &UpdateRestorationServiceUnavailable{}
}

// WithPayload adds the payload to the update restoration service unavailable response
func (o *UpdateRestorationServiceUnavailable) WithPayload(payload *models.APIResponse) *UpdateRestorationServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update restoration service unavailable response
func (o *UpdateRestorationServiceUnavailable) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRestorationServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRestorationGatewayTimeoutCode is the HTTP code returned for type UpdateRestorationGatewayTimeout
const UpdateRestorationGatewayTimeoutCode int = 504

/*
UpdateRestorationGatewayTimeout Gateway timeout. TOC controller did not reply.

swagger:response updateRestorationGatewayTimeout
*/
type UpdateRestorationGatewayTimeout struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateRestorationGatewayTimeout creates UpdateRestorationGatewayTimeout with default headers values
func NewUpdateRestorationGatewayTimeout() *UpdateRestorationGatewayTimeout {

	return &UpdateRestorationGatewayTimeout{}
}

// WithPayload adds the payload to the update restoration gateway timeout response
func (o *UpdateRestorationGatewayTimeout) WithPayload(payload *models.APIResponse) *UpdateRestorationGatewayTimeout {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update restoration gateway timeout response
func (o *UpdateRestorationGatewayTimeout) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRestorationGatewayTimeout) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(504)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
