// Code generated by go-swagger; DO NOT EDIT.

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetQuotaHandlerFunc turns a function with the right signature into a get quota handler
type GetQuotaHandlerFunc func(GetQuotaParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetQuotaHandlerFunc) Handle(params GetQuotaParams) middleware.Responder {
	return fn(params)
}

// GetQuotaHandler interface for that can handle valid get quota params
type GetQuotaHandler interface {
	Handle(GetQuotaParams) middleware.Responder
}

// NewGetQuota creates a new http.Handler for the get quota operation
func NewGetQuota(ctx *middleware.Context, handler GetQuotaHandler) *GetQuota {
	return &GetQuota{Context: ctx, Handler: handler}
}

/*
	GetQuota swagger:route GET /quotas quota getQuota

# Refresh quota info

Retrieve all quotas set
*/
type GetQuota struct {
	Context *middleware.Context
	Handler GetQuotaHandler
}

func (o *GetQuota) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetQuotaParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
