// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/gyk4j/toc/toc/restapi/operations/archive"
	"github.com/gyk4j/toc/toc/restapi/operations/backup"
	logops "github.com/gyk4j/toc/toc/restapi/operations/log"
	"github.com/gyk4j/toc/toc/restapi/operations/quota"
	"github.com/gyk4j/toc/toc/restapi/operations/restoration"
	"github.com/gyk4j/toc/toc/restapi/operations/synchronization"
)

// NewTocAPI creates a new Toc instance
func NewTocAPI(spec *loads.Document) *TocAPI {
	return &TocAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		ArchiveArchiveDataHandler: archive.ArchiveDataHandlerFunc(func(params archive.ArchiveDataParams) middleware.Responder {
			return middleware.NotImplemented("operation archive.ArchiveData has not yet been implemented")
		}),
		LogExportLogHandler: logops.ExportLogHandlerFunc(func(params logops.ExportLogParams) middleware.Responder {
			return middleware.NotImplemented("operation log.ExportLog has not yet been implemented")
		}),
		ArchiveGetArchiveHandler: archive.GetArchiveHandlerFunc(func(params archive.GetArchiveParams) middleware.Responder {
			return middleware.NotImplemented("operation archive.GetArchive has not yet been implemented")
		}),
		ArchiveGetArchiveByIDHandler: archive.GetArchiveByIDHandlerFunc(func(params archive.GetArchiveByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation archive.GetArchiveByID has not yet been implemented")
		}),
		BackupGetBackupHandler: backup.GetBackupHandlerFunc(func(params backup.GetBackupParams) middleware.Responder {
			return middleware.NotImplemented("operation backup.GetBackup has not yet been implemented")
		}),
		BackupGetBackupByIDHandler: backup.GetBackupByIDHandlerFunc(func(params backup.GetBackupByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation backup.GetBackupByID has not yet been implemented")
		}),
		QuotaGetQuotaHandler: quota.GetQuotaHandlerFunc(func(params quota.GetQuotaParams) middleware.Responder {
			return middleware.NotImplemented("operation quota.GetQuota has not yet been implemented")
		}),
		RestorationGetRestorationHandler: restoration.GetRestorationHandlerFunc(func(params restoration.GetRestorationParams) middleware.Responder {
			return middleware.NotImplemented("operation restoration.GetRestoration has not yet been implemented")
		}),
		RestorationGetRestorationByIDHandler: restoration.GetRestorationByIDHandlerFunc(func(params restoration.GetRestorationByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation restoration.GetRestorationByID has not yet been implemented")
		}),
		BackupNewBackupHandler: backup.NewBackupHandlerFunc(func(params backup.NewBackupParams) middleware.Responder {
			return middleware.NotImplemented("operation backup.NewBackup has not yet been implemented")
		}),
		RestorationNewRestorationHandler: restoration.NewRestorationHandlerFunc(func(params restoration.NewRestorationParams) middleware.Responder {
			return middleware.NotImplemented("operation restoration.NewRestoration has not yet been implemented")
		}),
		SynchronizationNewSynchronizationHandler: synchronization.NewSynchronizationHandlerFunc(func(params synchronization.NewSynchronizationParams) middleware.Responder {
			return middleware.NotImplemented("operation synchronization.NewSynchronization has not yet been implemented")
		}),
	}
}

/*TocAPI An API to create backup and restoration */
type TocAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// ArchiveArchiveDataHandler sets the operation handler for the archive data operation
	ArchiveArchiveDataHandler archive.ArchiveDataHandler
	// LogExportLogHandler sets the operation handler for the export log operation
	LogExportLogHandler logops.ExportLogHandler
	// ArchiveGetArchiveHandler sets the operation handler for the get archive operation
	ArchiveGetArchiveHandler archive.GetArchiveHandler
	// ArchiveGetArchiveByIDHandler sets the operation handler for the get archive by Id operation
	ArchiveGetArchiveByIDHandler archive.GetArchiveByIDHandler
	// BackupGetBackupHandler sets the operation handler for the get backup operation
	BackupGetBackupHandler backup.GetBackupHandler
	// BackupGetBackupByIDHandler sets the operation handler for the get backup by Id operation
	BackupGetBackupByIDHandler backup.GetBackupByIDHandler
	// QuotaGetQuotaHandler sets the operation handler for the get quota operation
	QuotaGetQuotaHandler quota.GetQuotaHandler
	// RestorationGetRestorationHandler sets the operation handler for the get restoration operation
	RestorationGetRestorationHandler restoration.GetRestorationHandler
	// RestorationGetRestorationByIDHandler sets the operation handler for the get restoration by Id operation
	RestorationGetRestorationByIDHandler restoration.GetRestorationByIDHandler
	// BackupNewBackupHandler sets the operation handler for the new backup operation
	BackupNewBackupHandler backup.NewBackupHandler
	// RestorationNewRestorationHandler sets the operation handler for the new restoration operation
	RestorationNewRestorationHandler restoration.NewRestorationHandler
	// SynchronizationNewSynchronizationHandler sets the operation handler for the new synchronization operation
	SynchronizationNewSynchronizationHandler synchronization.NewSynchronizationHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *TocAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *TocAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *TocAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *TocAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *TocAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *TocAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *TocAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *TocAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *TocAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the TocAPI
func (o *TocAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ArchiveArchiveDataHandler == nil {
		unregistered = append(unregistered, "archive.ArchiveDataHandler")
	}
	if o.LogExportLogHandler == nil {
		unregistered = append(unregistered, "log.ExportLogHandler")
	}
	if o.ArchiveGetArchiveHandler == nil {
		unregistered = append(unregistered, "archive.GetArchiveHandler")
	}
	if o.ArchiveGetArchiveByIDHandler == nil {
		unregistered = append(unregistered, "archive.GetArchiveByIDHandler")
	}
	if o.BackupGetBackupHandler == nil {
		unregistered = append(unregistered, "backup.GetBackupHandler")
	}
	if o.BackupGetBackupByIDHandler == nil {
		unregistered = append(unregistered, "backup.GetBackupByIDHandler")
	}
	if o.QuotaGetQuotaHandler == nil {
		unregistered = append(unregistered, "quota.GetQuotaHandler")
	}
	if o.RestorationGetRestorationHandler == nil {
		unregistered = append(unregistered, "restoration.GetRestorationHandler")
	}
	if o.RestorationGetRestorationByIDHandler == nil {
		unregistered = append(unregistered, "restoration.GetRestorationByIDHandler")
	}
	if o.BackupNewBackupHandler == nil {
		unregistered = append(unregistered, "backup.NewBackupHandler")
	}
	if o.RestorationNewRestorationHandler == nil {
		unregistered = append(unregistered, "restoration.NewRestorationHandler")
	}
	if o.SynchronizationNewSynchronizationHandler == nil {
		unregistered = append(unregistered, "synchronization.NewSynchronizationHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *TocAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *TocAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *TocAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *TocAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *TocAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *TocAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the toc API
func (o *TocAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *TocAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/archives"] = archive.NewArchiveData(o.context, o.ArchiveArchiveDataHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/logs"] = logops.NewExportLog(o.context, o.LogExportLogHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/archives"] = archive.NewGetArchive(o.context, o.ArchiveGetArchiveHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/archives/{archiveId}"] = archive.NewGetArchiveByID(o.context, o.ArchiveGetArchiveByIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/backups"] = backup.NewGetBackup(o.context, o.BackupGetBackupHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/backups/{backupId}"] = backup.NewGetBackupByID(o.context, o.BackupGetBackupByIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/quotas"] = quota.NewGetQuota(o.context, o.QuotaGetQuotaHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/restorations"] = restoration.NewGetRestoration(o.context, o.RestorationGetRestorationHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/restorations/{restorationId}"] = restoration.NewGetRestorationByID(o.context, o.RestorationGetRestorationByIDHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/backups"] = backup.NewNewBackup(o.context, o.BackupNewBackupHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/restorations"] = restoration.NewNewRestoration(o.context, o.RestorationNewRestorationHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/synchronizations"] = synchronization.NewNewSynchronization(o.context, o.SynchronizationNewSynchronizationHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *TocAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *TocAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *TocAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *TocAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *TocAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
