// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gyk4j/toc/toc-backend/models"
)

// GetBackupsOKCode is the HTTP code returned for type GetBackupsOK
const GetBackupsOKCode int = 200

/*
GetBackupsOK Backup info retrieved

swagger:response getBackupsOK
*/
type GetBackupsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Backup `json:"body,omitempty"`
}

// NewGetBackupsOK creates GetBackupsOK with default headers values
func NewGetBackupsOK() *GetBackupsOK {

	return &GetBackupsOK{}
}

// WithPayload adds the payload to the get backups o k response
func (o *GetBackupsOK) WithPayload(payload []*models.Backup) *GetBackupsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backups o k response
func (o *GetBackupsOK) SetPayload(payload []*models.Backup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Backup, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBackupsForbiddenCode is the HTTP code returned for type GetBackupsForbidden
const GetBackupsForbiddenCode int = 403

/*
GetBackupsForbidden Forbidden from querying backup info

swagger:response getBackupsForbidden
*/
type GetBackupsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBackupsForbidden creates GetBackupsForbidden with default headers values
func NewGetBackupsForbidden() *GetBackupsForbidden {

	return &GetBackupsForbidden{}
}

// WithPayload adds the payload to the get backups forbidden response
func (o *GetBackupsForbidden) WithPayload(payload *models.APIResponse) *GetBackupsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backups forbidden response
func (o *GetBackupsForbidden) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBackupsNotFoundCode is the HTTP code returned for type GetBackupsNotFound
const GetBackupsNotFoundCode int = 404

/*
GetBackupsNotFound Backup not found

swagger:response getBackupsNotFound
*/
type GetBackupsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBackupsNotFound creates GetBackupsNotFound with default headers values
func NewGetBackupsNotFound() *GetBackupsNotFound {

	return &GetBackupsNotFound{}
}

// WithPayload adds the payload to the get backups not found response
func (o *GetBackupsNotFound) WithPayload(payload *models.APIResponse) *GetBackupsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backups not found response
func (o *GetBackupsNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBackupsMethodNotAllowedCode is the HTTP code returned for type GetBackupsMethodNotAllowed
const GetBackupsMethodNotAllowedCode int = 405

/*
GetBackupsMethodNotAllowed Bad request

swagger:response getBackupsMethodNotAllowed
*/
type GetBackupsMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBackupsMethodNotAllowed creates GetBackupsMethodNotAllowed with default headers values
func NewGetBackupsMethodNotAllowed() *GetBackupsMethodNotAllowed {

	return &GetBackupsMethodNotAllowed{}
}

// WithPayload adds the payload to the get backups method not allowed response
func (o *GetBackupsMethodNotAllowed) WithPayload(payload *models.APIResponse) *GetBackupsMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backups method not allowed response
func (o *GetBackupsMethodNotAllowed) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupsMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBackupsInternalServerErrorCode is the HTTP code returned for type GetBackupsInternalServerError
const GetBackupsInternalServerErrorCode int = 500

/*
GetBackupsInternalServerError TOC controller error

swagger:response getBackupsInternalServerError
*/
type GetBackupsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBackupsInternalServerError creates GetBackupsInternalServerError with default headers values
func NewGetBackupsInternalServerError() *GetBackupsInternalServerError {

	return &GetBackupsInternalServerError{}
}

// WithPayload adds the payload to the get backups internal server error response
func (o *GetBackupsInternalServerError) WithPayload(payload *models.APIResponse) *GetBackupsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backups internal server error response
func (o *GetBackupsInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBackupsServiceUnavailableCode is the HTTP code returned for type GetBackupsServiceUnavailable
const GetBackupsServiceUnavailableCode int = 503

/*
GetBackupsServiceUnavailable Service unavailable

swagger:response getBackupsServiceUnavailable
*/
type GetBackupsServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBackupsServiceUnavailable creates GetBackupsServiceUnavailable with default headers values
func NewGetBackupsServiceUnavailable() *GetBackupsServiceUnavailable {

	return &GetBackupsServiceUnavailable{}
}

// WithPayload adds the payload to the get backups service unavailable response
func (o *GetBackupsServiceUnavailable) WithPayload(payload *models.APIResponse) *GetBackupsServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backups service unavailable response
func (o *GetBackupsServiceUnavailable) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupsServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
